### ISSUE TITLE
can't find file about train_Net.py

### ISSUE THREAD

**Issue by junedgar** [Lxyzgf/MTCNN-TF#1]
hi, thank you for your share.

I couldn't find the file about train_Net.py which you described  in `prepare_data/gen12_run.sh`.

**Comment by jimeffry** [comment]
first, I am sorry about that. I have a lot work to do, so I don't have  enough time to complete the file ReadMe.md.  You will find the file train_Net.py  in ./Project_root_dir/train_models/. If you have any other questions, please write here, thankyou.

**Comment by junedgar** [comment]
@Lxyzgf  
hi , thank you for your reply!
I encountered another problem. When train data put into the P_Net_W, it got the error:
`ValueError: Negative dimension size caused by subtracting 3 from 2 for 'conv3/Conv2D' (op: 'Conv2D') with input shapes: [256,2,2,64], [3,3,64,128].`
The input images' size is 12x12，but there do three times pooling with strade 2 which lead to Negative dimension occurred.


![1532409699296](https://user-images.githubusercontent.com/17995658/43118656-660a54e0-8f45-11e8-9135-aea11c64539e.jpg)

**Comment by jimeffry** [comment]
@junedgar 
Hi, the P_Net_W is designed for task of Pedestrian detection. And I find  that the MTCNN is not suitable  for Pedestrian detection.  If you plan to implement the task of Pedestrian detection, I suggest that you do it in other ways, for example Faster-RCNN or FCN. Actually, the input size of P_Net_W maybe 48x48. For the task of Face detection, please use P_Net. Thankyou, for your attention.

**Comment by junedgar** [comment]
Get it, thank you for reply !
