### ISSUE TITLE
Anchor比例问题

### ISSUE THREAD

**Issue by ghost** [Lxyzgf/MTCNN-TF#3]
如果是行人的话，就应该修改Anchor比例，不能再是正方形了？是不是可以这么理解，修改为矩形，效果更好一些。那么大佬是如何修改的啊，方便留个联系方式嘛

**Comment by jimeffry** [comment]
行人的话，anchor比例确实需要调整，经实验验证，效果太差，可能是Pnet网络太小不足以表示复杂的行人特征。

**Comment by ghost** [comment]
谢谢，已经调整成功，效果还不错。
